--download-archive 'archive.txt'
--retries infinite
--fragment-retries infinite
--file-access-retries infinite
--mtime
--embed-metadata
--write-info-json
--write-description
--write-thumbnail
--embed-thumbnail
--write-comments
--parse-metadata "%(title)s:%(meta_title)s"
--write-subs
--audio-multistreams
--video-multistreams
--live-from-start
--verbose
